const express = require('express')
const router = express.Router()

const authRouter = require('./auth-router')
const adminProductRouter = require('./admin-product-router')
const accountRouter = require('./account-router')
const orderRouter = require('./order-router')
const userRouter = require('./user-router')
const categoryRouter = require('./category-router')
const chatRouter = require('./chat-router')
const adminOrderRouter = require('./admin-order-router')
const settingRouter = require('./admin-setting-router')
const productRouter = require('./product-router')
const commonRouter = require('./common-router')

const { verifyToken } = require('../middlewares/verify-token')
const { verifyAdmin } = require('../middlewares/verify-admin')
const { verifyStaffAndAdmin } = require('../middlewares/verify-staff-or-admin')

router.use('/auth', authRouter)
router.use('/category', categoryRouter)
router.use('/setting', settingRouter)
router.use('/', verifyToken)
router.use('/common', commonRouter)
// router.use('/admin', verifyAdmin)
router.use('/admin/manage-product', verifyAdmin, adminProductRouter)
router.use('/admin/account', verifyAdmin, accountRouter)
router.use('/admin/chat', verifyStaffAndAdmin, chatRouter)
router.use('/admin/order', verifyStaffAndAdmin, adminOrderRouter)
router.use('/admin/setting', verifyStaffAndAdmin, settingRouter)
router.use('/user', userRouter)
router.use('/', orderRouter)
router.use('/chat', chatRouter)
router.use('/product', productRouter)

module.exports = router
